export 'package:wholecake/views/products/products_inventory.dart';
export 'package:wholecake/views/supplies/products_supplies.dart';
export 'package:wholecake/views/products/products_toexpire.dart';
export 'package:wholecake/views/products/products_view.dart';
export 'package:wholecake/views/products/products_add.dart';
export 'package:wholecake/views/products/products_edit.dart';
export 'package:wholecake/views/supplies/products_inputs_recipt.dart';
export 'package:wholecake/views/products/products_filter_view.dart';
export 'package:wholecake/views/products/products_category_view.dart';
