class ProductoEjemplo {
  final int id;
  final String name;
  final String category;
  final int price;
  int quantity;
  final String image;

  ProductoEjemplo(
      {required this.id,
      required this.name,
      required this.category,
      required this.price,
      required this.quantity,
      required this.image});
}

List<ProductoEjemplo> pastryProducts = [
  ProductoEjemplo(
    id: 1,
    name: "Torta de chocolate",
    category: "Tortas",
    price: 8000,
    quantity: 5,
    image: "assets/images/ejemplo/imagen1.jpg",
  ),
  ProductoEjemplo(
    id: 2,
    name: "Croissant de almendra",
    category: "Croissants",
    price: 1500,
    quantity: 10,
    image: "assets/images/ejemplo/imagen2.jpg",
  ),
  ProductoEjemplo(
    id: 3,
    name: "Cupcake de vainilla",
    category: "Cupcakes",
    price: 2000,
    quantity: 8,
    image: "assets/images/ejemplo/imagen3.jpg",
  ),
  ProductoEjemplo(
    id: 4,
    name: "Éclair de café",
    category: "Éclairs",
    price: 2500,
    quantity: 6,
    image: "assets/images/ejemplo/imagen4.jpg",
  ),
  ProductoEjemplo(
    id: 5,
    name: "Galleta de avena y pasas",
    category: "Galletas",
    price: 500,
    quantity: 15,
    image: "assets/images/ejemplo/imagen5.jpg",
  ),
  ProductoEjemplo(
    id: 6,
    name: "Tartaleta de frutos rojos",
    category: "Tartaletas",
    price: 1800,
    quantity: 7,
    image: "assets/images/ejemplo/imagen6.jpg",
  ),
  ProductoEjemplo(
    id: 7,
    name: "Brownie de nueces",
    category: "Brownies",
    price: 2500,
    quantity: 6,
    image: "assets/images/ejemplo/imagen7.jpg",
  ),
  ProductoEjemplo(
    id: 8,
    name: "Macarons de pistacho",
    category: "Macarons",
    price: 3000,
    quantity: 12,
    image: "assets/images/ejemplo/imagen8.jpg",
  ),
  ProductoEjemplo(
    id: 9,
    name: "Cannoli de crema",
    category: "Otros",
    price: 2000,
    quantity: 9,
    image: "assets/images/ejemplo/imagen9.jpg",
  ),
  ProductoEjemplo(
    id: 10,
    name: "Torta de limón",
    category: "Tortas",
    price: 7500,
    quantity: 4,
    image: "assets/images/ejemplo/imagen10.jpg",
  ),
  ProductoEjemplo(
    id: 11,
    name: "Berlines rellenos de dulce de leche",
    category: "Berlines",
    price: 1200,
    quantity: 10,
    image: "assets/images/ejemplo/imagen11.jpg",
  ),
  ProductoEjemplo(
    id: 12,
    name: "Tarta de manzana",
    category: "Tartas",
    price: 6000,
    quantity: 6,
    image: "assets/images/ejemplo/imagen12.jpg",
  ),
  ProductoEjemplo(
    id: 13,
    name: "Galletas de chispas de chocolate",
    category: "Galletas",
    price: 400,
    quantity: 20,
    image: "assets/images/ejemplo/imagen13.jpg",
  ),
  ProductoEjemplo(
    id: 14,
    name: "Profiteroles de crema",
    category: "Otros",
    price: 2500,
    quantity: 8,
    image: "assets/images/ejemplo/imagen14.jpg",
  ),
  ProductoEjemplo(
    id: 15,
    name: "Torta de zanahoria",
    category: "Tortas",
    price: 7000,
    quantity: 3,
    image: "assets/images/ejemplo/imagen15.jpg",
  ),
  ProductoEjemplo(
    id: 16,
    name: "Croissant de chocolate",
    category: "Croissants",
    price: 1800,
    quantity: 10,
    image: "assets/images/ejemplo/imagen16.jpg",
  ),
  ProductoEjemplo(
    id: 17,
    name: "Cupcake de fresa",
    category: "Cupcakes",
    price: 2200,
    quantity: 6,
    image: "assets/images/ejemplo/imagen17.jpg",
  ),
  ProductoEjemplo(
    id: 18,
    name: "Éclair de chocolate",
    category: "Éclairs",
    price: 2800,
    quantity: 7,
    image: "assets/images/ejemplo/imagen18.jpg",
  ),
  ProductoEjemplo(
    id: 19,
    name: "Galleta de mantequilla",
    category: "Galletas",
    price: 600,
    quantity: 12,
    image: "assets/images/ejemplo/imagen19.jpg",
  ),
  ProductoEjemplo(
    id: 20,
    name: "Tarta de nueces y caramelo",
    category: "Tartas",
    price: 8500,
    quantity: 5,
    image: "assets/images/ejemplo/imagen20.jpg",
  ),
  ProductoEjemplo(
    id: 21,
    name: "Croissant de queso",
    category: "Croissants",
    price: 2000,
    quantity: 8,
    image: "assets/images/ejemplo/imagen21.jpg",
  ),
  ProductoEjemplo(
    id: 22,
    name: "Cupcake de chocolate blanco",
    category: "Cupcakes",
    price: 2300,
    quantity: 9,
    image: "assets/images/ejemplo/imagen22.jpg",
  ),
  ProductoEjemplo(
    id: 23,
    name: "Éclair de frambuesa",
    category: "Éclairs",
    price: 2600,
    quantity: 4,
    image: "assets/images/ejemplo/imagen23.jpg",
  ),
  ProductoEjemplo(
    id: 24,
    name: "Galleta de chocolate y avellanas",
    category: "Galletas",
    price: 700,
    quantity: 15,
    image: "assets/images/ejemplo/imagen24.jpg",
  ),
  ProductoEjemplo(
    id: 25,
    name: "Tarta de frutas tropicales",
    category: "Tartas",
    price: 7800,
    quantity: 6,
    image: "assets/images/ejemplo/imagen25.jpg",
  ),
  ProductoEjemplo(
    id: 26,
    name: "Croissant de mermelada de frutos rojos",
    category: "Croissants",
    price: 1700,
    quantity: 10,
    image: "assets/images/ejemplo/imagen26.jpg",
  ),
  ProductoEjemplo(
    id: 27,
    name: "Cupcake de chocolate y avellanas",
    category: "Cupcakes",
    price: 2100,
    quantity: 8,
    image: "assets/images/ejemplo/imagen27.jpg",
  ),
  ProductoEjemplo(
    id: 28,
    name: "Éclair de vainilla",
    category: "Éclairs",
    price: 2400,
    quantity: 5,
    image: "assets/images/ejemplo/imagen28.jpg",
  ),
  ProductoEjemplo(
    id: 29,
    name: "Galleta de mantequilla y nueces",
    category: "Galletas",
    price: 550,
    quantity: 14,
    image: "assets/images/ejemplo/imagen29.jpg",
  ),
  ProductoEjemplo(
    id: 30,
    name: "Torta de maracuyá",
    category: "Tortas",
    price: 7200,
    quantity: 4,
    image: "assets/images/ejemplo/imagen30.jpg",
  ),
  ProductoEjemplo(
    id: 31,
    name: "Croissant de almendra y chocolate",
    category: "Croissants",
    price: 1900,
    quantity: 9,
    image: "assets/images/ejemplo/imagen31.jpg",
  ),
  ProductoEjemplo(
    id: 32,
    name: "Cupcake de arándanos",
    category: "Cupcakes",
    price: 2300,
    quantity: 7,
    image: "assets/images/ejemplo/imagen32.jpg",
  ),
  ProductoEjemplo(
    id: 33,
    name: "Éclair de limón",
    category: "Éclairs",
    price: 2600,
    quantity: 4,
    image: "assets/images/ejemplo/imagen33.jpg",
  ),
  ProductoEjemplo(
    id: 34,
    name: "Galleta de chocolate blanco y almendras",
    category: "Galletas",
    price: 650,
    quantity: 12,
    image: "assets/images/ejemplo/imagen34.jpg",
  ),
];
